# Generated by Django 5.1.7 on 2025-03-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('mobile', models.CharField(max_length=13, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
